-- ============================================================
-- ADAMA SMART CITY
-- Smart Waste Management System
-- PostgreSQL + PostGIS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS postgis;


-- ============================================================
-- BINS
-- Physical smart waste bins and their GIS locations
-- ============================================================

CREATE TABLE bins (
    id BIGSERIAL PRIMARY KEY,

    bin_id VARCHAR(50) NOT NULL UNIQUE,

    geom GEOGRAPHY(POINT, 4326) NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'NORMAL',

    data_source VARCHAR(20) NOT NULL DEFAULT 'HARDWARE',

    last_seen_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_bins_data_source
        CHECK (data_source IN ('HARDWARE', 'SIMULATED'))
);


-- ============================================================
-- DEVICES
-- Electronic device installed in a bin
-- ============================================================

CREATE TABLE devices (
    id BIGSERIAL PRIMARY KEY,

    device_id VARCHAR(100) NOT NULL UNIQUE,

    bin_id VARCHAR(50) NOT NULL,

    device_type VARCHAR(50) DEFAULT 'ESP32',

    firmware_version VARCHAR(50),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_devices_bin
        FOREIGN KEY (bin_id)
        REFERENCES bins(bin_id)
        ON DELETE CASCADE
);


-- ============================================================
-- BIN READINGS
-- Historical sensor telemetry
--
-- Every MQTT telemetry message creates one row.
-- ============================================================

CREATE TABLE bin_readings (
    id BIGSERIAL PRIMARY KEY,

    bin_id VARCHAR(50) NOT NULL,

    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    fill_level_pct DOUBLE PRECISION,

    fill_distance DOUBLE PRECISION,

    temperature DOUBLE PRECISION,

    smoke_value DOUBLE PRECISION,

    smoke_status VARCHAR(30),

    human_distance DOUBLE PRECISION,

    lid_status VARCHAR(30),

    system_status VARCHAR(30),

    CONSTRAINT fk_bin_readings_bin
        FOREIGN KEY (bin_id)
        REFERENCES bins(bin_id)
        ON DELETE CASCADE
);


-- ============================================================
-- DEVICE STATUS
-- Historical device connectivity/health
-- ============================================================

CREATE TABLE device_status (
    id BIGSERIAL PRIMARY KEY,

    device_id VARCHAR(100) NOT NULL,

    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    online BOOLEAN NOT NULL DEFAULT TRUE,

    signal_strength DOUBLE PRECISION,

    battery_level DOUBLE PRECISION,

    firmware_version VARCHAR(50),

    CONSTRAINT fk_device_status_device
        FOREIGN KEY (device_id)
        REFERENCES devices(device_id)
        ON DELETE CASCADE
);


-- ============================================================
-- JANITORS
-- Waste collection personnel
-- ============================================================

CREATE TABLE janitors (
    id BIGSERIAL PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    phone VARCHAR(50),

    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',

    geom GEOGRAPHY(POINT, 4326),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- ALERTS
-- Events generated by the decision/alert engine
-- ============================================================

CREATE TABLE alerts (
    id BIGSERIAL PRIMARY KEY,

    bin_id VARCHAR(50) NOT NULL,

    alert_type VARCHAR(50) NOT NULL,

    severity VARCHAR(20) NOT NULL,

    message TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    resolved_at TIMESTAMPTZ,

    assigned_janitor_id BIGINT,

    CONSTRAINT fk_alert_bin
        FOREIGN KEY (bin_id)
        REFERENCES bins(bin_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_alert_janitor
        FOREIGN KEY (assigned_janitor_id)
        REFERENCES janitors(id)
        ON DELETE SET NULL
);


-- ============================================================
-- COLLECTIONS
-- Actual waste collection events
-- ============================================================

CREATE TABLE collections (
    id BIGSERIAL PRIMARY KEY,

    bin_id VARCHAR(50) NOT NULL,

    janitor_id BIGINT,

    collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    fill_level_before DOUBLE PRECISION,

    notes TEXT,

    status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',

    CONSTRAINT fk_collection_bin
        FOREIGN KEY (bin_id)
        REFERENCES bins(bin_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_collection_janitor
        FOREIGN KEY (janitor_id)
        REFERENCES janitors(id)
        ON DELETE SET NULL
);


-- ============================================================
-- COLLECTION ROUTES
-- Planned collection routes
-- ============================================================

CREATE TABLE collection_routes (
    id BIGSERIAL PRIMARY KEY,

    route_name VARCHAR(150) NOT NULL,

    janitor_id BIGINT,

    route_date DATE,

    status VARCHAR(30) NOT NULL DEFAULT 'PLANNED',

    route_geom GEOGRAPHY(LINESTRING, 4326),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_route_janitor
        FOREIGN KEY (janitor_id)
        REFERENCES janitors(id)
        ON DELETE SET NULL
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_bins_geom
ON bins
USING GIST (geom);

CREATE INDEX idx_janitors_geom
ON janitors
USING GIST (geom);

CREATE INDEX idx_collection_routes_geom
ON collection_routes
USING GIST (route_geom);


CREATE INDEX idx_bin_readings_bin_id
ON bin_readings(bin_id);

CREATE INDEX idx_bin_readings_recorded_at
ON bin_readings(recorded_at);

CREATE INDEX idx_bin_readings_bin_time
ON bin_readings(bin_id, recorded_at DESC);


CREATE INDEX idx_device_status_device_id
ON device_status(device_id);

CREATE INDEX idx_device_status_recorded_at
ON device_status(recorded_at);

CREATE INDEX idx_device_status_device_time
ON device_status(device_id, recorded_at DESC);


CREATE INDEX idx_alerts_bin_id
ON alerts(bin_id);

CREATE INDEX idx_alerts_created_at
ON alerts(created_at);

CREATE INDEX idx_alerts_unresolved
ON alerts(resolved_at)
WHERE resolved_at IS NULL;


CREATE INDEX idx_collections_bin_id
ON collections(bin_id);

CREATE INDEX idx_collections_janitor_id
ON collections(janitor_id);

CREATE INDEX idx_collections_collected_at
ON collections(collected_at);


-- ============================================================
-- INITIAL BINS
-- ============================================================

INSERT INTO bins (
    bin_id,
    geom,
    status,
    data_source
)
VALUES
(
    'BIN-001',
    ST_SetSRID(
        ST_MakePoint(39.2700, 8.5400),
        4326
    )::geography,
    'NORMAL',
    'HARDWARE'
),
(
    'BIN-002',
    ST_SetSRID(
        ST_MakePoint(39.2720, 8.5415),
        4326
    )::geography,
    'NORMAL',
    'SIMULATED'
),
(
    'BIN-003',
    ST_SetSRID(
        ST_MakePoint(39.2740, 8.5385),
        4326
    )::geography,
    'NORMAL',
    'SIMULATED'
);


-- ============================================================
-- INITIAL DEVICES
-- ============================================================

INSERT INTO devices (
    device_id,
    bin_id,
    device_type
)
VALUES
(
    'ESP32-BIN-001',
    'BIN-001',
    'ESP32'
),
(
    'SIM-BIN-002',
    'BIN-002',
    'SIMULATOR'
),
(
    'SIM-BIN-003',
    'BIN-003',
    'SIMULATOR'
);


-- ============================================================
-- VIEW: LATEST BIN STATUS
-- Used by the GIS map and bin dashboard
-- ============================================================

CREATE VIEW latest_bin_status AS

SELECT
    b.bin_id,

    ST_Y(b.geom::geometry) AS latitude,
    ST_X(b.geom::geometry) AS longitude,

    b.geom,
    b.status,
    b.data_source,
    b.last_seen_at,

    r.recorded_at,

    r.fill_level_pct,
    r.fill_distance,
    r.temperature,
    r.smoke_value,
    r.smoke_status,
    r.human_distance,
    r.lid_status,
    r.system_status

FROM bins b

LEFT JOIN LATERAL (
    SELECT *
    FROM bin_readings br
    WHERE br.bin_id = b.bin_id
    ORDER BY br.recorded_at DESC
    LIMIT 1
) r ON TRUE;


-- ============================================================
-- VIEW: LATEST DEVICE STATUS
-- ============================================================

CREATE VIEW latest_device_status AS

SELECT
    d.device_id,
    d.bin_id,

    ds.recorded_at,
    ds.online,
    ds.signal_strength,
    ds.battery_level,
    ds.firmware_version

FROM devices d

LEFT JOIN LATERAL (
    SELECT *
    FROM device_status
    WHERE device_status.device_id = d.device_id
    ORDER BY device_status.recorded_at DESC
    LIMIT 1
) ds ON TRUE;


-- ============================================================
-- VIEW: PENDING ALERTS
-- ============================================================

CREATE VIEW pending_alerts_view AS

SELECT
    a.id,
    a.bin_id,
    a.alert_type,
    a.severity,
    a.message,
    a.created_at,
    a.assigned_janitor_id

FROM alerts a

WHERE a.resolved_at IS NULL;

-- ============================================================
-- USERS
-- System users and administrators
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,

    username VARCHAR(100) NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    role VARCHAR(30) NOT NULL DEFAULT 'user',

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_users_role
        CHECK (role IN ('admin', 'user'))
);